# This is a basic workflow to help you get started with Actions

name: Naiveproxy Docker

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manually trigger'
        required: true
env:
 TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          #registry: docker.pkg.github.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-naive
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
              zjy7723/naiveproxy:latest
              zjy7723/naiveproxy:${{ steps.date.outputs.today }}  
